--  Autogenerated with DRAKON Editor 1.33
package Geometry.Lists is

   type Cell is
      record
         Next : access Cell;
         Element : Pointer;
      end record;

   type List is
      access Cell;

   type Pointer is
      access Object'Class;

   procedure Add_To_List (
      The_List : in out List;
      Obj_Ptr : Pointer
   )
   ;

end Geometry.Lists;
