--  Autogenerated with DRAKON Editor 1.33
package Geometry.Magic is

   function MO (
      OC : Object'Class
   ) return Float;

   function Moment (
      OC : Object'Class
   ) return Float;

end Geometry.Magic;
