--  Autogenerated with DRAKON Editor 1.33
package Geometry.Triangles is

   type Triangle is
      new Object with
      record
         A, B, C : Float;
      end record;

   overriding
   function Area (
      T : Triangle
   ) return Float;

   overriding
   function MI (
      T : Triangle
   ) return Float;

   overriding
   function Name (
      T : Triangle
   ) return String;

end Geometry.Triangles;
