--  Autogenerated with DRAKON Editor 1.33
package Geometry.Squares is

   type Square is
      new Object with
      record
         Side : Float;
      end record;

   overriding
   function Area (
      S : Square
   ) return Float
   ;

   overriding
   function MI (
      S : Square
   ) return Float
   ;

   overriding
   function Name (
      S : Square
   ) return String
   ;

end Geometry.Squares;
