--  Autogenerated with DRAKON Editor 1.33
package body Geometry.Points is

   overriding
   function Area (
      P : Point
   ) return Float is
   begin
      return 0.0;
   end Area;

   overriding
   function MI (
      P : Point
   ) return Float is
   begin
      return 0.0;
   end MI;

   overriding
   function Name (
      P : Point
   ) return String is
   begin
      return "Point";
   end Name;

end Geometry.Points;
