--  Autogenerated with DRAKON Editor 1.33
with Ada.Numerics;
package body Geometry.Circles is

   overriding
   function Area (
      C : Circle
   ) return Float
   is
   begin
      return Ada.Numerics.Pi * C.Radius**2;
   end Area;

   overriding
   function MI (
      C : Circle
   ) return Float
   is
   begin
      return 0.5 * C.Area * C.Radius**2;
   end MI;

   overriding
   function Name (
      C : Circle
   ) return String
   is
   begin
      return "Circle";
   end Name;

end Geometry.Circles;
