--  Autogenerated with DRAKON Editor 1.33
package Geometry.Circles is

   type Circle is
      new Object with
      record
         Radius : Float;
      end record;

   overriding
   function Area (
      C : Circle
   ) return Float;

   overriding
   function MI (
      C : Circle
   ) return Float;

   overriding
   function Name (
      C : Circle
   ) return String;

end Geometry.Circles;
