--  Autogenerated with DRAKON Editor 1.33
package body Geometry.Magic is

   function MO (
      OC : Object'Class
   ) return Float
   is
   begin
      return OC.MI + OC.Area * OC.Distance**2;
   end MO;

   function Moment (
      OC : Object'Class
   ) return Float
   is
   begin
      return OC.X_Coord * OC.Area;
   end Moment;

end Geometry.Magic;
