--  Autogenerated with DRAKON Editor 1.33
with Geometry.Lists;
package Geometry.IO is

   function Get_Circle  return Lists.Pointer;

   function Get_Square  return Lists.Pointer;

   function Get_Triangle  return Lists.Pointer;

end Geometry.IO;
