--  Autogenerated with DRAKON Editor 1.33
package Geometry.Points is

   type Point is
      new Object with
      null record;

   overriding
   function Area (
      P : Point
   ) return Float;

   overriding
   function MI (
      P : Point
   ) return Float;

   overriding
   function Name (
      P : Point
   ) return String;

end Geometry.Points;
