--  Autogenerated with DRAKON Editor 1.33
package Geometry is

   type Object is abstract tagged
      record
         X_Coord : Float;
         Y_Coord : Float;
      end record;

   function Area (
      O : Object
   ) return Float is abstract;

   function Distance (
      O : Object
   ) return Float;

   function MI (
      O : Object
   ) return Float is abstract;

   function Name (
      O : Object
   ) return String is abstract;

end Geometry;
